### ISSUE TITLE
Fails to build on macOS with Ruby 3.4.7

### ISSUE THREAD

**Issue by coder2000** [ruby/curses#118]
### Environment
- **Ruby version:** 3.4.7
- **Curses gem version:** 1.5.3
- **Operating System:** macOS 26.1 (Build 25B78)
- **Architecture:** arm64 (Apple Silicon)
- **Compiler:** Apple clang version 21.0.0
- **ncurses:** 6.5 (installed via Homebrew at `/opt/homebrew/opt/ncurses`)

### Description
The curses gem fails to compile on Ruby 3.4.7 during the native extension build. The build fails at the `chtype` type conversion test in `extconf.rb`.

### Steps to Reproduce
```bash
gem install curses -- --use-system-libraries --with-ncurses-dir=/opt/homebrew/opt/ncurses
```

### Error Output
From `gem_make.out`:
```
checking for convertible type of chtype... failed
*** extconf.rb failed ***
Could not create Makefile due to some reason, probably lack of necessary
libraries and/or headers.
```

### Root Cause
From analyzing `mkmf.log`, the issue appears to be twofold:

1. **Ruby 3.4.7 header warning**: Ruby's internal header (`ruby/internal/core/rstring.h:398`) triggers a compiler warning:
   ```
   warning: default initialization of an object of type 'struct RString' with const member 
   leaves the object uninitialized [-Wdefault-const-init-field-unsafe]
   ```

2. **chtype conversion test failure**: The test to determine the C type equivalent of `chtype` fails with:
   ```
   conftest.c:8:20: error: 'conftest_const' declared as an array with a negative size
   int conftest_const[((rbcv_typedef_)-1 < 0) ? 1 : -1];
   ```

The test program attempts to determine if `chtype` is signed, but the compilation fails before it can complete the type detection logic.

### Attempted Workarounds
- Setting `--with-cflags="-Wno-error=default-const-init-field-unsafe"` does not resolve the issue
- The warning flag is applied correctly, but the chtype conversion test still fails

### Relevant Log Excerpt
```
convertible_int: checking for convertible type of chtype... -------------------- failed

DYLD_LIBRARY_PATH=.:/Users/coder2000/.local/share/mise/installs/ruby/3.4.7/lib ASAN_OPTIONS=detect_leaks=0 "clang -I/Users/coder2000/.local/share/mise/installs/ruby/3.4.7/include/ruby-3.4.0/arm64-darwin25 -I/Users/coder2000/.local/share/mise/installs/ruby/3.4.0/ruby/backward -I/Users/coder2000/.local/share/mise/installs/ruby/3.4.7/include/ruby-3.4.0 -I. -D_XOPEN_SOURCE -D_DARWIN_C_SOURCE -D_DARWIN_UNLIMITED_SELECT -D_REENTRANT   -Wno-error=default-const-init-field-unsafe -arch arm64  -c conftest.c"
...
conftest.c:8:20: error: 'conftest_const' declared as an array with a negative size
    8 | int conftest_const[((rbcv_typedef_)-1 < 0) ? 1 : -1];
```

### Expected Behavior
The gem should compile successfully and the `chtype` type conversion should be detected properly.

### Additional Notes
- This appears to be specific to Ruby 3.4.x on macOS with Apple Silicon
- The same issue may affect other recent Ruby 3.4.x versions
- ncurses libraries are found correctly - all function checks pass up until the `chtype` conversion test

### Question
Is there a known incompatibility with Ruby 3.4.x's internal headers and the type detection logic in `extconf.rb`? Would it be possible to update the type detection mechanism to be more robust against compiler warnings in Ruby headers?

**Comment by coder2000** [comment]
That works, thanks. Hopefully the issue can be resolved where it's not needed.

**Comment by shugo** [comment]
I've heard from @nobu that the Ruby 3.4.7 header warning has already been fixed in the ruby_3_4 branch.
We are investigating the chtype conversion test failure now.

**Comment by shugo** [comment]
@coder2000 
It seems that the issue was fixed by https://github.com/ruby/ruby/commit/2bb6fe3854e2a4854bb89bfce4eaaea9d848fd1b and has been backported to Ruby 3.4.8.

Could you try Ruby 3.4.8?

**Comment by shugo** [comment]
@nobu 
> I can't reproduce the second issue "chtype conversion test failure" with Apple clang version 17.0.0. And Apple clang version 21 doesn't look released yet. Are you using developers beta or something?

The "chtype conversion test failure" is a symptom of the "Ruby 3.4.7 header warning". The sequence is:

  1. try_signedness succeeds fine (no -Werror there); chtype is correctly identified as unsigned
  2. convertible_int then searches for the compatible type using try_compile(..., werror: true), which appends -Werror
  3. Every candidate type (unsigned int, unsigned long, etc.) fails; not because of a type mismatch, but because
  -Werror promotes the rstring.h warning to a fatal error

**Comment by shugo** [comment]
I believe this issue was fixed in Ruby 3.4.8 (see https://bugs.ruby-lang.org/issues/21629), so I'm closing it. Please feel free to reopen if it still reproduces with Ruby 3.4.8 or later.
